server:
  port: 8080

spring:
  profiles: dev
  servlet:
    multipart:
      enabled: true
      resolve-lazily: false
      max-file-size: 100MB
      max-request-size: 100MB
    max-file-size: 100MB
    max-request-size: 100MB
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效
    template-loader-path: classpath:/templates   #默认 加载目录

mybatis:
  mapper-locations: classpath:/mapper/*.xml





