# 低版本
fileserver:
  file-expired-time: 604800000
  minio:
    access-key: Fatri2019
    secret-key: Fatri2019
    region: cn-south-rack-1
    server:
      host: 10.50.42.16
      secure: false
      port: 9000

spring:
  datasource:
    url: jdbc:mysql://10.50.42.16:3306/cms_longyuan_group?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: Fatri2021!@#
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    cassandra:
      repositories:
        type: none
      cluster-name: cassandra_cluster
      keyspace-name: jarvis_datastore
      contact-points: 10.50.42.16
      username: cassandra
      password: cassandra
      fetch-size: 100
      port: 9042
      local-datacenter: datacenter1
