server:
  port: 8080
spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://47.118.51.155:3306/spring_tansiactional?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: rtuser
    password: gs@2022#
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    cassandra:
      keyspace-name: jarvis_datastore
      #entity-base-packages:
      contact-points: 172.28.2.206
      port: 9042
      cluster-name: cassandra_cluster
      username: root
      password: roots
      local-datacenter: datacenter1

mybatis:
  mapper-locations: classpath:/mapper/*.xml


