
minio:
  endpoint: http://10.50.42.16:9000
  accessKey: Fatri2019
  secretKey: Fatri2019
  bucketName: images

spring:
  datasource:
    url: jdbc:mysql://10.50.42.16:3306/cms_longyuan_group?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: Fatri2021!@#
    driver-class-name: com.mysql.cj.jdbc.Driver

#  data:
#    cassandra:
#      keyspace-name: jarvis_datastore
#      #entity-base-packages:
#      contact-points: 10.50.42.16
#      port: 9042
#      cluster-name: cassandra_cluster
#      username: cassandra
#      password: cassandra
#      local-datacenter: datacenter1
#      connection:
#        connect-timeout: 10
  data:
    cassandra:
      repositories:
        type: none
      cluster-name: cassandra_cluster
      keyspace-name: jarvis_datastore
      contact-points: 10.50.42.16
      username: cassandra
      password: cassandra
      fetch-size: 100
      port: 9042
